# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

fib_nums = [1, 2]
fib_even_num_sum = 2

while fib_nums[-1] < 4000000:
    fib_num = fib_nums[-1] + fib_nums[-2]
    fib_nums.append(fib_num)
    fib_even_num_sum += fib_num if fib_num % 2 == 0 else 0
    fib_nums.pop(0) if(len(fib_nums) == 4) else 0

print(fib_even_num_sum)
